### ISSUE TITLE
"import SyntaxNetWrapper" error if wrapper called outside /root/syntaxnet-wrapper

### ISSUE THREAD

**Issue by ecamaj** [short-edition/syntaxnet-wrapper#7]
Used your Dockerfile as starting image, and if I try to import your module

`from syntaxnet_wrapper.wrapper import SyntaxNetWrapper`

from any folder instead of /root/syntaxnet-wrapper, I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/syntaxnet_wrapper/wrapper.py", line 6, in <module>
    from syntaxnet_wrapper.parser_eval import SyntaxNetConfig, SyntaxNetProcess
  File "/usr/local/lib/python2.7/dist-packages/syntaxnet_wrapper/parser_eval.py", line 48, in <module>
    from syntaxnet.ops import gen_parser_ops
  File "syntaxnet.py", line 3, in <module>
    from syntaxnet_wrapper.wrapper import SyntaxNetWrapper
ImportError: cannot import name SyntaxNetWrapper
```

Didn't look too much into it, but it think it might be something wrong with path definitions in parser_eval.py.

**Comment by ecamaj** [comment]
It was funny coincidence that I had "syntaxnet.py" file I folder from where I started python that made the mess with imports.
